apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: new-php-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: example.lab
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: new-php-service
            port:
              number: 80